theme = "archie"
baseURL = 'https://haysberg.io/'
languageCode = 'en-us'
title = 'teo@interwebs:~/$'
author = "TÃ©o HaÃ¿s"
staticDir = ['static']
copyright = "Â© TÃ©o HaÃ¿s"

[params]
	mode="toggle" # color-mode â†’ light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = """
        â”¬â”´â”¬â”´â”¤â€¢á´¥â€¢Ê”â”œâ”¬â”´â”¬â”´
    Hello, I'm TÃ©o, your local SRE baguette boi.
    I mostly use ğ–ğ–šğ–‡ğ–Šğ–—ğ–“ğ–Šğ–™ğ–Šğ–˜ and other tools such as ğ–†ğ–“ğ–˜ğ–ğ–‡ğ–‘ğ–Š and ğ–ğ–Šğ–‘ğ–’ because I'm a (ã¤â–€Â¯â–€ )ã¤ ğŸ”¥ cool kid ğŸ”¥
    """
	mathjax = false
	katex = false

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/haysberg"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/teo-hays"

[[params.social]]
name = "LinkedIn"
icon = "mail"
url = "mailto:teo@haysberg.io"