baseURL = 'https://haysberg.io/'
languageCode = 'en-us'
title = 'root@interwebs:~/$'
author = "TÃ©o HaÃ¿s"
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[Params]
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "TÃ©o HaÃ¿s"
  [Params.Terminal]
  scheme = "Hemisu Dark"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "root"
  pcName = "interwebs"
  workDir = "haysberg"
  profile = "me.txt"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
  commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  # terminalDelay = 20 : deprecated

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file

  # activityDelay = 5 : deprecated

  description = """
  â”¬â”´â”¬â”´â”¤â€¢á´¥â€¢Ê”â”œâ”¬â”´â”¬â”´

  Hello, I'm TÃ©o, your local SRE baguette boi.

  I mostly use ğ–ğ–šğ–‡ğ–Šğ–—ğ–“ğ–Šğ–™ğ–Šğ–˜ and other tools 
  such as ğ–†ğ–“ğ–˜ğ–ğ–‡ğ–‘ğ–Š and ğ–ğ–Šğ–‘ğ–’ because I'm a 
  (ã¤â–€Â¯â–€ )ã¤ ğŸ”¥ cool kid ğŸ”¥

  Check out my links or you'll face
  tÌ¶Ì›Ì¡Ì¦hÌ¸Ì„Í‰Ì™eÌµÍŒÌÌ Ì´ÌÍ˜Í“cÌµÌ›Í‡oÌ·Ì•ÌÍšÌºnÌµÍ—Í„ÌÌªsÌ·Í›Í„ÌºeÌµÌ“Ì™Í‡qÌ´Í„ÍŠÍ•uÌ¸Í—ÍˆÍ”eÌ·ÌŠÌ„Ì nÌ´ÌŒÌ¨cÌ¶ÌŒÌÍ”Í‡eÌ´Ì€Ì¹sÌ·ÍŠÌ¡.

  """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "my_links"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["(âœ§á´—âœ§âœ¿) GitHub", "https://github.com/haysberg"],
    ["â¸œ(ï½¡Ëƒ áµ• Ë‚)â¸â™¡ LinkedIn", "https://www.linkedin.com/in/teo-hays"],
    ["â˜€(â–€U â–€-Í ) Cool resume", "cool_resume.pdf"],
    ["Email âœ§( à¥â€¢âŒ„â€¢ )â—ğŸ’Œâ—Ÿ( â€¢âŒ„â€¢ )âœ§", "mailto:teo@haysberg.io"]
  ]

  [module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"
