base_url = "https://haysberg.io/"
title = "✨teo@interwebs✨"
description = "Check out my links !"

compile_sass = true
generate_feeds = true

taxonomies = [
    { name = "tags" },
    { name = "categories" },
    { name = "contexts" },
]

[markdown]
highlight_code = true

[extra]
author = "Téo Haÿs"
